<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ToDoTree.App</RootNamespace>
    <AssemblyName>ToDoTree</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToDoTree.Core\ToDoTree.Core.csproj" />
  </ItemGroup>

</Project>
